'use strict';

const
  Promise          = require('bluebird'),
  _                = require("lodash"),
  exec             = Promise.promisify(require("child_process").exec),
{ writeFileAsync } = Promise.promisifyAll(require('fs')),
  YAML             = require('yamljs'),
  util             = require('util')

const writeRelease = (path, data) => {
  if (! data) {
    throw new Error(`trying to write null data to ${path}`)
  }

  const filename = `${_.toLower(data.kind)}.yml`
  let output = "# DO NOT EDIT THIS FILE BY HAND! IT IS GENERATED FROM A TEMPLATE\n"
  output += dumpYaml(data)

  // attempt to parse the yaml, to make sure it's valid
  parseYaml(output)

  return writeFileAsync(`${path}/${filename}`, output)
}
module.exports.writeRelease = writeRelease

const printStderr = (err) => {
  console.error(err.message)
}
module.exports.printStderr = printStderr

const inspect = (...input) => {
  return console.log(util.inspect(input, false, null))
}
module.exports.inspect = inspect

const dumpYaml = (obj) => {
  // switch to inline dump after 99 levels of indentation, use 2 spaces for
  // indentation
  return YAML.stringify(obj, 99, 2)
}
module.exports.dumpYaml = dumpYaml

const parseYaml = (str) => {
  return YAML.parse(str)
}
module.exports.parseYaml = parseYaml

const printFormatFrame = (frame) => {
  return `${frame.commit.revision} (${frame.commit.date}) ${frame.commit.author.name}
    ${frame.commit.subject}
    component: ${frame.component.name}
    version: ${frame.component.version}
    valid: ${frame.valid ? 'VALID' : 'INVALID'}
    action: ${frame.action}
    rationale: ${_.join(frame.rationale, '; ')}
  `
}
module.exports.printFormatFrame = printFormatFrame

const releaseMessage = (frame) => {
  return `k8s-${frame.commit.revision} ${frame.action} `
  + `${frame.component.name}:${frame.component.version} `
  + `(${frame.commit.revision}) [${frame.commit.subject}]`
}
module.exports.releaseMessage = releaseMessage

const releasePath = (componentName) => {
  return `./k8s/releases/${componentName}`
}
module.exports.releasePath = releasePath

const addExecRes = (commit, command, path) => {
  return exec(command)
  .then(result => {
    return _.set(commit, path, _.trim(result))
  })
  .error(err => {
    commit.valid = false
    commit.errors.push(err)

    return commit
  })
}
module.exports.addExecRes = addExecRes

